### ISSUE TITLE
App Crash at Startup with 3.3.0 & 3.3.1

### ISSUE THREAD

**Issue by efeurun** [adaptyteam/AdaptySDK-Unity#17]
Hello,

After updating from version 2.9 to 3.3.X, we started experiencing a crash on Android app startup. I have tried both versions 3.3.0 and 3.3.1, and they both exhibit the same crash.

On the other hand, the iOS builds work fine and do not have any issues.

Below is the crash log from startup:

```
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime FATAL EXCEPTION: main
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime Process: com.dopiverse.app, PID: 30738
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.installProvider(ActivityThread.java:7755)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7291)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7187)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.access$2200(ActivityThread.java:296)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:107)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:213)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8178)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime Caused by: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2121)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2094)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at android.app.ActivityThread.installProvider(ActivityThread.java:7750)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	... 10 more
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:37)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:25)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	... 16 more
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ReportFragment$ActivityInitializationListener
2025/03/20 15:15:01.254 30738 30738 Error AndroidRuntime 	... 19 more

```

**Comment by vladd-g** [comment]
Hello @efeurun 

Could you please check if [this](https://adapty.io/docs/sdk-installation-unity#add-kotlin-plugin-to-your-project) helps?

**Comment by efeurun** [comment]
Hi again @vladd-g , Importing Kotlin fixed our crash even though we aren't using paywall builder. I'm closing this issue, thanks.
